import { ApiProperty } from "@nestjs/swagger";
import { IsInt, IsString, MaxLength, Min, MinLength } from "class-validator";

export class PutSceneDto {
  @ApiProperty({
    description: "Scene version generated by client",
    example: 42,
  })
  @IsInt()
  @Min(0)
  sceneVersion!: number;

  @ApiProperty({
    description: "AES IV in base64 format",
    example: "sN9+YFe7K7P4fJd4d6m0Aw==",
  })
  @IsString()
  @MinLength(8)
  @MaxLength(4096)
  iv!: string;

  @ApiProperty({
    description: "Encrypted scene payload in base64 format",
    example: "AAABBBCCCDDDEEE...",
  })
  @IsString()
  @MinLength(8)
  @MaxLength(10_000_000)
  ciphertext!: string;
}
